
package br.com.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "WSTest", targetNamespace = "http://ws.com.br/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface WSTest {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "yahooMethod", targetNamespace = "http://ws.com.br/", className = "br.com.ws.YahooMethod")
    @ResponseWrapper(localName = "yahooMethodResponse", targetNamespace = "http://ws.com.br/", className = "br.com.ws.YahooMethodResponse")
    @Action(input = "http://ws.com.br/WSTest/yahooMethodRequest", output = "http://ws.com.br/WSTest/yahooMethodResponse")
    public String yahooMethod(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
