
package br.com.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "yahoo", targetNamespace = "http://ws.com.br/", wsdlLocation = "http://d19236:9090/JAX-WB-Test/yahoo?wsdl")
public class Yahoo
    extends Service
{

    private final static URL YAHOO_WSDL_LOCATION;
    private final static WebServiceException YAHOO_EXCEPTION;
    private final static QName YAHOO_QNAME = new QName("http://ws.com.br/", "yahoo");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://d19236:9090/JAX-WB-Test/yahoo?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        YAHOO_WSDL_LOCATION = url;
        YAHOO_EXCEPTION = e;
    }

    public Yahoo() {
        super(__getWsdlLocation(), YAHOO_QNAME);
    }

    public Yahoo(WebServiceFeature... features) {
        super(__getWsdlLocation(), YAHOO_QNAME, features);
    }

    public Yahoo(URL wsdlLocation) {
        super(wsdlLocation, YAHOO_QNAME);
    }

    public Yahoo(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, YAHOO_QNAME, features);
    }

    public Yahoo(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public Yahoo(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns WSTest
     */
    @WebEndpoint(name = "WSTestPort")
    public WSTest getWSTestPort() {
        return super.getPort(new QName("http://ws.com.br/", "WSTestPort"), WSTest.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns WSTest
     */
    @WebEndpoint(name = "WSTestPort")
    public WSTest getWSTestPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://ws.com.br/", "WSTestPort"), WSTest.class, features);
    }

    private static URL __getWsdlLocation() {
        if (YAHOO_EXCEPTION!= null) {
            throw YAHOO_EXCEPTION;
        }
        return YAHOO_WSDL_LOCATION;
    }

}
